language: node_js
node_js:
- "8"
dist: trusty
env: 
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
    - client/node_modules
services:
  - mongodb    
install:
  - npm install
script:
  - nohup npm start &